### ISSUE TITLE
Register in the General registry?

### ISSUE THREAD

**Issue by DilumAluthge** [MasonProtter/Gaius.jl#19]

**Comment by chriselrod** [comment]
Should perhaps work on performance a little first.

**Comment by DilumAluthge** [comment]
Makes sense! Maybe tag 0.3.0 instead?

It would be nice to register 0.3.0 in General now though.

**Comment by MasonProtter** [comment]
As it says on the readme, I don’t really have any particular plans to continue to work on this package. 

It was a fun little project, but ultimately, I think there are better approaches like Tullio.jl and PaddedMatrices.jl. 

I don’t think it’d be a good idea to put this on the general registry or tag v1.0.

**Comment by DilumAluthge** [comment]
My main motivation for getting Gaius into the General registry is that Gaius seems to be a good set of additional tests for LoopVectorization. By getting Gaius into the PkgEval runs, we'll have an additional way of detecting regressions in LoopVectorization and VectorizationBase.

It's entirely up to you!

But FWIW I think it's fine to register a package even if we don't anticipate any further development on the package.

**Comment by DilumAluthge** [comment]
(My favorite part of this package is how accessible the code is to beginners such as myself that are just starting to get interested in this kind of thing. But I suppose that's not a particularly compelling reason for registering.)

**Comment by chriselrod** [comment]
I don't mind more tests. It also has almost 4x the stars of PaddedMatrices!

**Comment by DilumAluthge** [comment]
Yeah I'll retract the 1.0 suggestion.

**Comment by chriselrod** [comment]
> (My favorite part of this package is how accessible the code is to beginners such as myself that are just starting to get interested in this kind of thing. But I suppose that's not a particularly compelling reason for registering.)

High performance algorithms don't really need to be more complicated.

Want to help develop it?

**Comment by chriselrod** [comment]
Basically, high performance matmul:
![](https://user-images.githubusercontent.com/8043603/78473523-47bced00-770f-11ea-89b1-82f4bc28d178.png)
LoopVectorization does the microkernel and 2 loops.

All you'd need to do is write loops 3, 4, and 5 ;).

**Comment by MasonProtter** [comment]
> My main motivation for getting Gaius into the General registry is that Gaius seems to be a good set of additional tests for LoopVectorization. By getting Gaius into the PkgEval runs, we'll have an additional way of detecting regressions in LoopVectorization and VectorizationBase.

> (My favorite part of this package is how accessible the code is to beginners such as myself that are just starting to get interested in this kind of thing. But I suppose that's not a particularly compelling reason for registering.)

Yeah, that makes sense! Let's get this on the registry then!

**Comment by MasonProtter** [comment]
@JuliaRegistrator register

**Comment by DilumAluthge** [comment]
> Want to help develop it?

I'm happy to help!

**Comment by MasonProtter** [comment]
I've made you a collaborator in this repo.

**Comment by chriselrod** [comment]
@DilumAluthge Here's an example:
```julia
using LoopVectorization, VectorizationBase, ArrayInterface
import Gaius: PointerMatrix, blocked_mul!
using ArrayInterface: One, StaticInt

Base.@pure function block_sizes(::Type{T}) where {T}
    L1, L2, L3, L4 = VectorizationBase.CACHE_SIZE
    L1c, L2c, L3c, L4c = VectorizationBase.CACHE_COUNT
    @assert L3 isa Int
    @assert L1c == L2c == VectorizationBase.NUM_CORES

    # L1 ÷= sizeof(T)
    L2 ÷= sizeof(T)
    L3 ÷= sizeof(T)

    W = VectorizationBase.pick_vector_width(T)
    Mr, Nr = LoopVectorization.mᵣ, LoopVectorization.nᵣ
    MrW = Mr * W

    Mk_Kk = sqrt(0.75L2)
    Mk = MrW * round(Int, Mk_Kk / MrW, RoundDown)
    Kk = round(Int, Mk_Kk, RoundDown)
    Nk = round(Int, 0.5L3 / (Kk * Nr)) * Nr
    Mk, Kk, Nk
end
function block_sizes_static(::Type{T}) where {T}
    Mk, Kk, Nk = block_sizes(T)
    StaticInt(Mk), StaticInt(Kk), StaticInt(Nk)
end

@code_typed block_sizes(Float64)
@code_typed block_sizes_static(Float64)

check_sizes(::StaticInt{M}, ::StaticInt{M}) where {M} = StaticInt{M}()
check_sizes(::StaticInt{M}, ::StaticInt{N}) where {M,N} = throw("$M ≠ $N")
check_sizes(::StaticInt{M}, m) where {M} = (@assert M == m; StaticInt{M}())
check_sizes(m, ::StaticInt{M}) where {M} = (@assert M == m; StaticInt{M}())
check_sizes(m, n) = (@assert m == n; m)

function PointerMatrix(Bptr::Ptr{T}, (M,N), padcols::Bool = false) where {T}
    st = VectorizationBase.static_sizeof(T)
    _M = padcols ? VectorizationBase.align(M, T) : M
    Bsptr = stridedpointer( # Should maybe add a more convenient column major constructor
        Bptr, ArrayInterface.Contiguous{1}(), ArrayInterface.ContiguousBatch{0}(), ArrayInterface.StrideRank{(1,2)}(), (st, _M*st), (One(),One())
    )
    PointerMatrix(Bsptr, (M,N))
end

function macrokernel!(C, A, B, α, β)
    @avx for n ∈ axes(C,2), m ∈ axes(C,1)
        Cmn = zero(eltype(C))
        for k ∈ axes(B,1)
            Cmn += A[m,k] * B[k,n]
        end
        C[m,n] = α * Cmn + β * C[m,n]
    end
end

const BCACHE = Vector{UInt8}(undef, VectorizationBase.CACHE_SIZE[3]);

function unsafe_copyto_avx!(B, A)
    @avx for i ∈ eachindex(B, A)
        B[i] = A[i]
    end
end

mutable struct MemoryBuffer{L,T}
    data::NTuple{L,T}
    MemoryBuffer{L,T}(::UndefInitializer) where {L,T} = new{L,T}()
end
Base.unsafe_convert(::Type{Ptr{T}}, m::MemoryBuffer) where {T} = Base.unsafe_convert(Ptr{T}, Base.pointer_from_objref(m))
@inline MemoryBuffer(::StaticInt{L}, ::Type{T}) where {L,T} = MemoryBuffer{L,T}(undef)
@inline function L2Buffer(::Type{T}) where {T}
    MemoryBuffer(StaticInt{VectorizationBase.CACHE_SIZE[2]}() ÷ VectorizationBase.static_sizeof(T), T)
end
    

function blocked_loop_mul!(C::AbstractMatrix{T}, A::AbstractMatrix{T}, B::AbstractMatrix{T}, _α = one(T), _β = zero(T)) where {T}
    Mk, Kk, Nk = block_sizes_static(T)
    MC, NC = ArrayInterface.size(C)
    MA, KA = ArrayInterface.size(A)
    KB, NB = ArrayInterface.size(B)
    M = check_sizes(MC, MA)
    K = check_sizes(KA, KB)
    N = check_sizes(NC, NB)

    Amem = L2Buffer(T)
    Aptr = Base.unsafe_convert(Ptr{T}, Amem);
    Bptr = Base.unsafe_convert(Ptr{T}, BCACHE);
    GC.@preserve Amem begin
        α = T(_α); 
        for n ∈ One():Nk:N
            nsize = min(Int(n + Nk), Int(N + 1)) - n
            β = T(_β)
            for k ∈ One():Kk:K
                ksize = min(Int(k + Kk), Int(K + 1)) - k
                Bblock = PointerMatrix(Bptr, (ksize,nsize))
                unsafe_copyto_avx!(Bblock, view(B, k:k+ksize-1, n:n+nsize-1))
                for m ∈ One():Mk:M
                    msize = min(Int(m + Mk), Int(M + 1)) - m

                    Ablock = PointerMatrix(Aptr, (msize, ksize), true)
                    unsafe_copyto_avx!(Ablock, view(A, m:m+msize-1, k:k+ksize-1))

                    Cblock = view(C, m:m+msize-1, n:n+nsize-1)
                    macrokernel!(Cblock, Ablock, Bblock, α, β)
                end
                β = one(T) # re-writing to the same blocks of `C`, so replace original factor with `1`
            end
        end
    end # GC.@preserve
    C
end
```
You may want to skip copying data if the matrices are smaller, adjust the block sizes, etc.
You'd probably want to add threading. That would also mean adjusting block sizes for medium sized matrices, to be able to have enough threads to work with.

On my laptop (after having previously compiled everything):
```julia
julia> M, K, N = 4000,4000,4000;

julia> A = rand(M,K); B = rand(K,N); C2 = A * B; C1 = similar(C2);

julia> blocked_loop_mul!(C1, A, B) ≈ C2
true

julia> @time blocked_loop_mul!(C1, A, B);
  2.152860 seconds

julia> @time blocked_mul!(C2, A, B);
  2.474929 seconds

julia> @time blocked_mul!(C2, A, B);
  2.443353 seconds

julia> @time blocked_loop_mul!(C1, A, B);
  2.089815 seconds
```

This is hopefully few enough lines of code to easily follow, but already performs quite well!

**Comment by DilumAluthge** [comment]
Fixed by https://github.com/JuliaRegistries/General/pull/26665
