### ISSUE TITLE
Change threading API

### ISSUE THREAD

**Issue by DilumAluthge** [MasonProtter/Gaius.jl#57]
See also: https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/25

**Comment by chriselrod** [comment]
Preferably, we'd either have separate functions, or (probably better) it'd just be an argument defaulting to something like `nthreads() > 1`.

**Comment by DilumAluthge** [comment]
I think separate functions might be better; otherwise, we have a bunch of `if ` statements.

**Comment by DilumAluthge** [comment]
Or maybe a compile-time constant argument.

**Comment by chriselrod** [comment]
I'm currently using separate function names in PaddedMatrices, but if you pass a value of `<= 1` for the number of threads (6th position argument to `jmult!`) it'll call `jmul!`.

So we could probably take a similar approach here.
