### ISSUE TITLE
Implement PointerVector to Support BLAS2 functions

### ISSUE THREAD

**Issue by MasonProtter** [MasonProtter/Gaius.jl#8]
I want to eventually add in some BLAS2 support (i.e. matrix vector products) but to do so I'll need to make a `PointerVector` type. 

Most of it is pretty straightforward just copy-pasting definitions with slight tweaks from `PointerMatrix` but I'm not sure about the `maybeview` function. As is, the matrix definition is
```julia
@inline Base.maybeview(A::PointerMatrix, r::UnitRange, c::UnitRange) = PointerMatrix(gesp(A.ptr, (first(r) - 1, (first(c) - 1))), (length(r), length(c)))
```
but I'm not exactly sure what `gesp` (https://github.com/chriselrod/VectorizationBase.jl/blob/master/src/vectorizable.jl#L262) does. Could you advise @chriselrod?

**Comment by chriselrod** [comment]
"get element strided pointer", like `gep` ([get element pointer](https://llvm.org/docs/LangRef.html#getelementptr-instruction), but returns a strided pointer.
What it's doing is getting the pointer corresponding to `A[first(r), first(c)]`. The minus 1s are because it assumes 0-based indexing.
