### ISSUE TITLE
Analyzing matrix-matrix multiplication performance degradation in "more balanced" branch

### ISSUE THREAD

**Issue by tkf** [MasonProtter/Gaius.jl#85]
This is the benchmark backing up the reason why I rolled back matrix-matrix multiplication in #83 (05417dc47e36d60a431e77ca58eb4030fd0f1cc1).

Here's the "speedup" of the target (7b4ba9a4fd33e66a3b0e09e1967fe2b168c953bf) with respect to the baseline (42b282075ac096d11fd836d79855e50c7213a53b).  The value smaller than 1 indicates it's slower with the target:

![image](https://user-images.githubusercontent.com/29282/137849566-060fae5e-8e42-4c2c-9ac9-162446abcfba.png)

Here's a more "raw data" plot, showing the speedup for each versions with respect to the performance in `julia --threads=1`:

![image](https://user-images.githubusercontent.com/29282/137849545-d6d1015e-b911-474c-9584-784cc50b16c8.png)

### Analyzing the task DAG

The above result was puzzling for me so I tried to figure out why. But the analysis itself confuses me more. I'm not sure if it's useful to share a confusing analysis. But, just as a record, here's where I stuck at now.

I used [TaskDAGAnalyzers.jl](https://github.com/tkf/TaskDAGAnalyzers.jl) to analyze the DAG created from matrix-matrix multiplication.  You can find the full script at: https://gist.github.com/tkf/94b1a4110d90f26251c1d2de4999cab2

**NOTE**: I'm not sure if TaskDAGAnalyzers.jl is doing the right thing ATM, partially because its output is puzzling.  So, take it with a grain of salt.

If I run Gaius.jl's GEMM with three 256x256 matrices, it reports the following metrics for target (c8a1e13caaf814e86e192be642a5a4f23a2b7511 which is equivalent to the first commit of #83):

```
TaskDAGAnalyzers.summary:
work: 1.6 ms (single-thread run-time T₁)
span: 109 μs (theoretical fastest run-time Tₒₒ)
parallelism (work/span): 14.872990869043585
```

and for baseline (08da3a7a7fbedfc50af17d3de14a542203b24fe2):

```
TaskDAGAnalyzers.summary:
work: 4.5 ms (single-thread run-time T₁)
span: 80 μs (theoretical fastest run-time Tₒₒ)
parallelism (work/span): 56.691479003345485
```

The result that span is shorter in the baseline is compatible with the above measurements.  OTOH, baseline has a larger amount of work.  If I believe this number, I'd expect that the target to perform well at least for low thread count.

#### DAG dump

The shape of the task DAG is expected in that the target has less sequential dependencies.

| Baseline | Target |
| --- | --- |
| 08da3a7a7fbedfc50af17d3de14a542203b24fe2 | c8a1e13caaf814e86e192be642a5a4f23a2b7511 |
| ![][baseline_dag.png] | ![][target_dag.png] |

[baseline_dag.png]: https://user-images.githubusercontent.com/29282/137849685-81d6df2c-b883-4912-bc0d-1ed5f05f0d8e.png
[target_dag.png]: https://user-images.githubusercontent.com/29282/137849699-0717b4d2-eb4f-425e-b6c1-d7ea4358e8dd.png

**Comment by chriselrod** [comment]
Can you add support for appending meta data to the task graph somehow?
Doesn't seem like it'd be possible without modifying the code you're analyzing, but I just think it'd be nice to see the sizes of the blocks at each point. 

What are the sizes of the matrices used for producing the graphs you attached?
