### ISSUE TITLE
Status check and auto-merge

### ISSUE THREAD

**Issue by tkf** [MasonProtter/Gaius.jl#86]
@MasonProtter What do you think about enabling status check and auto-merge?

**Comment by tkf** [comment]
I think we'll see the `Required` box on right like this

> ![image](https://user-images.githubusercontent.com/29282/138392212-788f8f9e-c27d-4405-a935-73c5c3664194.png)

in the PR if this is successfully enabled.

My setting for the above repo looks like

> ![image](https://user-images.githubusercontent.com/29282/138392109-ef729a69-e90c-40c0-b8a6-8d485bf1a394.png)

You'll need to include things like `Julia nightly/1 threads/ubuntu-latest/x64/pull_request` instead of `vanilla-test (nightly)` in my screenshot.

But this is really an optional thing. So please no worries if that's confusing.

**Comment by DilumAluthge** [comment]
> I only set them to be required on a subset of the tests, just Ubuntu with 1 and 2 threads and the coverage. Let me know if you want more checks required.

Just FYI, this means that GitHub will auto-merge a PR as soon as those checks pass, even if other checks end up failing.

**Comment by tkf** [comment]
FWIW, I usually mark all tests required, including the ones with Julia nightly unless it's very unstable

Anyway, I think it's working now! Thanks a lot!

> If desired, we can move this repo to an organization, which would allow us to have multiple admins, thus relieving some of the admin burden from Mason.

I agree it'd be nice to avoid bothering Mason by moving this to JuliaLinearAlgebra or sth but it's of course up to Mason :)
