### ISSUE TITLE
Gaius broken due to Static.StaticInt not being an integer

### ISSUE THREAD

**Issue by nathanaelbosch** [MasonProtter/Gaius.jl#91]
`Gaius._print_num_threads_warning` expects integers. But since Static v0.7, `Static.StaticInt` is not an integer anymore. Therefore, Gaius is currently broken:
```
julia> using Gaius
[ Info: Precompiling Gaius [bffe22d1-cb55-4f4e-ac2c-f4dd4bf58912]
ERROR: InitError: MethodError: no method matching _print_num_threads_warning(::Static.StaticInt{6}, ::Int64)
Closest candidates are:
  _print_num_threads_warning(::Integer, ::Integer) at ~/.julia/packages/Gaius/xYgac/src/init.jl:12
during initialization of module Gaius
```

This is the related issue on Static.jl: https://github.com/SciML/Static.jl/issues/73

Possible solutions would be to make `Static.StaticInt <: Integer` again, or to explicitly support `Static.StaticInt` in the corresponding Gaius functions.

**Comment by MasonProtter** [comment]
Should be fixed now on the latest version (v0.6.8) and will be available on the general registry when this goes through: https://github.com/JuliaRegistries/General/pull/82994
